id: I72ABEB2A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-04-05T10:29:34+00:00'
last_modified: '2022-06-10T10:38:28.102213+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN18534
  title: གསུང་ཐོར་བུ། བློ་ལྡན་ཤེས་རབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
